name = "budle-adjustment-primer"
uuid = "ff30b5d4-e3ae-47fd-a392-54f4089c98cc"
authors = ["Adam Jahraus <adamjahraus@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
